openapi: 3.1.0
info:
  title: Aldaleel Travel API
  version: '1.0'
  description: API specification for Aldaleel travel planning application

servers:
  - url: http://localhost:8000/api/v1
    description: Development server

components:
  schemas:
    Trip:
      type: object
      required:
        - destination
        - status
        - duration
        - startDate
        - endDate
      properties:
        id:
          type: string
          format: uuid
        destination:
          type: string
        status:
          type: string
          enum: [upcoming, planning, completed]
        duration:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        thumbnail:
          type: string
          format: uri
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /trips:
    get:
      summary: Get all trips
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of trips
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new trip
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
      responses:
        '201':
          description: Trip created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /trips/{tripId}:
    get:
      summary: Get trip by ID
      security:
        - bearerAuth: []
      parameters:
        - name: tripId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Trip details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '404':
          description: Trip not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'